id: AB92BB934
title: 'Excellent Intention: A Simple Fasting (Nyungne) Ritual'
type: translation
pechas:
- IE1DED393
- I3FB3BFA4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:42:57.730120
  last_modified_at: 2023-01-04 12:42:57.730139
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  IE1DED393/4771: 11DB
  I3FB3BFA4/98B5: 11DB
